language: csharp
dist: trusty
sudo: false
dotnet: 2.1
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - secure: "rMe0PRcgb2BeFoDpe1cp7NZ/9Qa9BGlYwcLD+f1Uz+GN/qbsRed1b6/c4t8pRJKs8HOfIw0IFDPArE6mvNrzdST6mHftqPa6+Nw6kTc3ylvNdMboY3D++SN/RJAojQWFfuCxSuW73pH2lgDDkUIiC8KOTfa2QkOFYKYJi79SnuEpnCuHduBE3OYOkd5S/dDaUkdY2TIEumEnzAgOIbel+nYLid89rxHrN3zD7mXHcnUhpDBd7+SkXYCr03wV7EeS+LOzx1qcsHUQAcziC8XO6/8A2Z/mKKhTVoUQoivNRkcnOyPEmcLMzht4H6shf+QjKvQ+wMxJ9T/BCAjyFWdTHR7h6ik49NKO/kwPA7NpTTzihuTKQAeAuHAWoD/Z26xpQxWl2JCxizF3Q58utNvCx3qZLSNbRmUxqnnU4tIIYEKXEwwrOc6HI+S/Hm5tGw9z/QtkdGxlxAupIOLuDkfBiSf2PsiurQegPXVkrYad3057e9jJhXQfGL6aNJoou949jioFw4fWTUC6NI6yZAwaOfE3cTmSTCneLwsEScV2+s6x6MYP/qNqS5/e/8P0yjrjuofPbo8yrtSTAI5jS9V4L21IDLthFPSOpM9kHWluXk0UqUVX+1N+UAEe7eeiHBWU8uLFDZbifhrsFanzZaPfiseGNlhpjgPvsMRwNNjN9qw="

script:
  - VERSION_SUFFIX="$(date +"%y%m%d")-$TRAVIS_BUILD_NUMBER"
  - dotnet pack src/Tmds.Varlink --configuration Release --version-suffix $VERSION_SUFFIX --output .
  - dotnet pack src/Tmds.Varlink.Tool --configuration Release --version-suffix $VERSION_SUFFIX --output .

after_success:
  - 'if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  curl -H "X-NuGet-ApiKey: $NUGET_APIKEY" -T src/Tmds.Varlink/Tmds.Varlink.*.nupkg https://www.myget.org/F/tmds/api/v2/package ;
  curl -H "X-NuGet-ApiKey: $NUGET_APIKEY" -T src/Tmds.Varlink.Tool/Tmds.Varlink.Tool.*.nupkg https://www.myget.org/F/tmds/api/v2/package ;
     fi'